options:
  thread-pool-size: 4
  debug: false
list:
  pre-page-size: 10
  up: '&d&l&m======================================='
  format: '&a{order} &b -> &6{key} &5- &b{name}'
  left: '  &b<-'
  page-info: '      &e{current}&5/&e{total}      '
  right: '&b->  '
  down: '&d&l&m======================================='

